### PR TITLE
hello added

### PR DESCRIPTION
**Pull request by jxn-dev**
Test

### CODE REVIEW

**Review by moisout — APPROVED** [review]
Sehr schlecht

**Comment by moisout** [comment]
> Sehr schlecht

Bitte hinterlassen Sie konstruktives feedback. Danke

**Comment by ckVendrix** [comment]
How dare you completing pr without me

**Comment by moisout** [comment]
I am the owner here

**Comment by ckVendrix** [comment]
You now have options to

- [x] say goodbye
- [x] dye
- [x] cry

**Pull request merged**
